INSERT INTO Team (name, shortName, abbr, id) VALUES ('Leicester City', 'Leicester', 'LEI', 26);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Everton', 'Everton', 'EVE', 7);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Chelsea', 'Chelsea', 'CHE', 4);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Crystal Palace', 'Crystal Palace', 'CRY', 6);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Arsenal', 'Arsenal', 'ARS', 1);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Aston Villa', 'Aston Villa', 'AVL', 2);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Bournemouth', 'Bournemouth', 'BOU', 127);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Stoke City', 'Stoke', 'STK', 42);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Sunderland', 'Sunderland', 'SUN', 29);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Tottenham Hotspur', 'Spurs', 'TOT', 21);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Swansea City', 'Swansea', 'SWA', 45);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Norwich City', 'Norwich', 'NOR', 14);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Southampton', 'Southampton', 'SOU', 20);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Newcastle United', 'Newcastle', 'NEW', 23);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Manchester United', 'Man Utd', 'MUN', 12);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('West Ham United', 'West Ham', 'WHU', 25);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Watford', 'Watford', 'WAT', 33);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('West Bromwich Albion', 'West Brom', 'WBA', 36);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Liverpool', 'Liverpool', 'LIV', 10);
INSERT INTO Team (name, shortName, abbr, id) VALUES ('Manchester City', 'Man City', 'MCI', 11);
